site_name: Knowledge Base
site_url: https://example.com
 
theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: pink
    - scheme: slate
      primary: deep purple
      accent: lime
  toggle:
    icon: material/weather-night
    name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - toc.integrate
 
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.emoji
  - pymdownx.tasklist
 
plugins:
  - search
  - mkdocs-breadcrumbs-plugin:
      delimiter: " / "
      use_page_titles: true
      home_text: "Home"
  - i18n:
      default_language: en
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: hi
          name: हिन्दी
          build: true
nav:
  - Home: index.md
  - Help:
      - Getting Started: help/getting-started.md
      - Features: help/features.md
      - FAQ: help/faq.md
  - हिन्दी: hi/index.md
 
extra:
  hero:
    title: "👋 Welcome to My Project"
    tagline: A modern documentation experience with a clean landing page
    image:
      src: assets/banner.jpeg


